version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5001:80"
    env_file:
      - variables.env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - webnet
    depends_on:
      - postgresDb

  postgresDb:
    image: postgres:latest
    container_name: postgresDb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: YouCan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrations
    entrypoint: ["dotnet", "ef", "database", "update", "--project", "/app/YouCan.Repository/YouCan.Repository.csproj"]
    depends_on:
      - postgresDb
    env_file:
      - variables.env
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
