version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5001:80"
    env_file:
      - variables.env
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgresDb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: YouCan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
